# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0092533990ed3921c9e89f89ed8773de81a901725ad0b614f502669aefee1052b16298bd3520c423b2ccb84cb02b22edebb5d8f731b185cea53897cfeaa9e6

test:
  secret_key_base: d055181e33f8bb7e55e1d9cd70694f5bf77f0d87c3c06958ce12011124c562824278867b1d0d19fd78e0d2488a8a0e5fdfeec03e552e04b83aff5bd5e5b13b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
